package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"text/template"
)

// ConfigRaw matches the structure of your iso-4217.json.
// Pointers for ISONum and NumToBasic handle the 'null' values (like in ZWB).
type ConfigRaw struct {
	Name         string `json:"name"`
	Demonym      string `json:"demonym"`
	MajorSingle  string `json:"majorSingle"`
	MajorPlural  string `json:"majorPlural"`
	ISONum       *int   `json:"ISOnum"`
	Symbol       string `json:"symbol"`
	SymbolNative string `json:"symbolNative"`
	MinorSingle  string `json:"minorSingle"`
	MinorPlural  string `json:"minorPlural"`
	ISODigits    int    `json:"ISOdigits"`
	Decimals     int    `json:"decimals"`
	NumToBasic   *int   `json:"numToBasic"`
}

const MaxSafeDecimals = 12

const fileTemplate = `// Code generated by gen_currencies; DO NOT EDIT.
package money

var currencyConfig = map[string]*Config{
{{- range . }}
	"{{ .ISOCode }}": {
		ISOCode:      "{{ .ISOCode }}",
		Name:         {{ printf "%q" .Name }},
		Demonym:      {{ printf "%q" .Demonym }},
		MajorSingle:  {{ printf "%q" .MajorSingle }},
		MajorPlural:  {{ printf "%q" .MajorPlural }},
		ISONum:       {{ if .ISONum }}{{ .ISONum }}{{ else }}0{{ end }},
		Symbol:       {{ printf "%q" .Symbol }},
		SymbolNative: {{ printf "%q" .SymbolNative }},
		MinorSingle:  {{ printf "%q" .MinorSingle }},
		MinorPlural:  {{ printf "%q" .MinorPlural }},
		ISODigits:    {{ .ISODigits }},
		Decimals:     {{ .Decimals }},
		NumToBasic:   {{ if .NumToBasic }}{{ .NumToBasic }}{{ else }}0{{ end }},
	},
{{- end }}
}
`

type TemplateData struct {
	ISOCode string
	ConfigRaw
}

func main() {
	// 1. Read the raw JSON data
	data, err := os.ReadFile("iso-4217.json")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading JSON: %v\n", err)
		os.Exit(1)
	}

	// 2. Parse into internal map
	var rawConfigs map[string]ConfigRaw
	if err := json.Unmarshal(data, &rawConfigs); err != nil {
		fmt.Fprintf(os.Stderr, "Error unmarshaling: %v\n", err)
		os.Exit(1)
	}

	// 3. Prepare and Sort data for deterministic output
	var sortedData []TemplateData
	for code, cfg := range rawConfigs {
		if cfg.Decimals > MaxSafeDecimals {
			fmt.Fprintf(os.Stderr, "Skipping %s: %d decimals exceeds limit\n", code, cfg.Decimals)
			continue
		}
		sortedData = append(sortedData, TemplateData{ISOCode: code, ConfigRaw: cfg})
	}

	sort.Slice(sortedData, func(i, j int) bool {
		return sortedData[i].ISOCode < sortedData[j].ISOCode
	})

	// 4. Generate the Go file
	f, err := os.Create("currencies.gen.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	tmpl := template.Must(template.New("gen").Parse(fileTemplate))
	if err := tmpl.Execute(f, sortedData); err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Successfully generated currencies.gen.go with sorted keys")
}
