package main

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"text/template"
)

// isoData is the ISO 4217 source, embedded at build time so the generator
// is independent of the working directory it is invoked from.
//
//go:embed iso-4217.json
var isoData []byte

// ConfigRaw matches the structure of your iso-4217.json.
// Pointers for ISONum and NumToBasic handle the 'null' values (like in ZWB).
type ConfigRaw struct {
	Name         string `json:"name"`
	Demonym      string `json:"demonym"`
	MajorSingle  string `json:"majorSingle"`
	MajorPlural  string `json:"majorPlural"`
	ISONum       *int   `json:"ISOnum"`
	Symbol       string `json:"symbol"`
	SymbolNative string `json:"symbolNative"`
	MinorSingle  string `json:"minorSingle"`
	MinorPlural  string `json:"minorPlural"`
	ISODigits    int    `json:"ISOdigits"`
	Decimals     int    `json:"decimals"`
	NumToBasic   *int   `json:"numToBasic"`
}

const MaxSafeDecimals = 12

const fileTemplate = `// Code generated by gen_currencies; DO NOT EDIT.
package money

var currencyConfig = map[string]*Currency{
{{- range . }}
	"{{ .ISOCode }}": {
		isoCode:      "{{ .ISOCode }}",
		symbol:       {{ printf "%q" .Symbol }},
		decimals:     {{ .Decimals }},
		isoNum:       {{ if .ISONum }}{{ .ISONum }}{{ else }}ISONumUnknown{{ end }},
		isoDigits:    {{ .ISODigits }},
		numToBasic:   {{ if .NumToBasic }}{{ .NumToBasic }}{{ else }}NumToBasicUnknown{{ end }},
		name:         {{ printf "%q" .Name }},
		demonym:      {{ printf "%q" .Demonym }},
		symbolNative: {{ printf "%q" .SymbolNative }},
		majorSingle:  {{ printf "%q" .MajorSingle }},
		majorPlural:  {{ printf "%q" .MajorPlural }},
		minorSingle:  {{ printf "%q" .MinorSingle }},
		minorPlural:  {{ printf "%q" .MinorPlural }},
	},
{{- end }}
}
`

type TemplateData struct {
	ISOCode string
	ConfigRaw
}

func main() {
	// 1. Parse the embedded JSON into an internal map.
	var rawConfigs map[string]ConfigRaw
	if err := json.Unmarshal(isoData, &rawConfigs); err != nil {
		fmt.Fprintf(os.Stderr, "Error unmarshaling: %v\n", err)
		os.Exit(1)
	}

	// 3. Prepare and Sort data for deterministic output
	var sortedData []TemplateData
	for code, cfg := range rawConfigs {
		if cfg.Decimals > MaxSafeDecimals {
			fmt.Fprintf(os.Stderr, "Skipping %s: %d decimals exceeds limit\n", code, cfg.Decimals)
			continue
		}
		sortedData = append(sortedData, TemplateData{ISOCode: code, ConfigRaw: cfg})
	}

	sort.Slice(sortedData, func(i, j int) bool {
		return sortedData[i].ISOCode < sortedData[j].ISOCode
	})

	// 4. Generate the Go file
	f, err := os.Create("currencies.gen.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	tmpl := template.Must(template.New("gen").Parse(fileTemplate))
	if err := tmpl.Execute(f, sortedData); err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Successfully generated currencies.gen.go with sorted keys")
}
