package main

import (
	"encoding/json"
	"fmt"
	"os"
	"text/template"
)

// ConfigRaw Internal representation for parsing JSON.
// We use pointers for NumbToBasic and ISONum to handle 'null' values in the JSON.
type ConfigRaw struct {
	Name         string `json:"name"`
	Demonym      string `json:"demonym"`
	MajorSingle  string `json:"majorSingle"`
	MajorPlural  string `json:"majorPlural"`
	ISONum       *int   `json:"ISOnum"`
	Symbol       string `json:"symbol"`
	SymbolNative string `json:"symbolNative"`
	MinorSingle  string `json:"minorSingle"`
	MinorPlural  string `json:"minorPlural"`
	ISODigits    int    `json:"ISOdigits"`
	Decimals     int    `json:"decimals"`
	NumToBasic   *int   `json:"numToBasic"`
}

const MaxSafeDecimals = 12 // Allows for ~9 million units of headroom. Adjust as needed.

const fileTemplate = `// Code generated by gen_currencies; DO NOT EDIT.
package money

var currencyConfig = map[string]*Config{
{{- range $code, $cfg := . }}
	"{{ $code }}": {
		ISOCode:      "{{ $code }}",
		Name:         {{ printf "%q" $cfg.Name }},
		Demonym:      {{ printf "%q" $cfg.Demonym }},
		MajorSingle:  {{ printf "%q" $cfg.MajorSingle }},
		MajorPlural:  {{ printf "%q" $cfg.MajorPlural }},
		ISONum:       {{ if $cfg.ISONum }}{{ $cfg.ISONum }}{{ else }}0{{ end }},
		Symbol:       {{ printf "%q" $cfg.Symbol }},
		SymbolNative: {{ printf "%q" $cfg.SymbolNative }},
		MinorSingle:  {{ printf "%q" $cfg.MinorSingle }},
		MinorPlural:  {{ printf "%q" $cfg.MinorPlural }},
		ISODigits:    {{ $cfg.ISODigits }},
		Decimals:     {{ $cfg.Decimals }},
		NumToBasic:   {{ if $cfg.NumToBasic }}{{ $cfg.NumToBasic }}{{ else }}0{{ end }},
	},
{{- end }}
}
`

func main() {
	// 1. Read the raw data
	data, err := os.ReadFile("iso-4217.json")
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Error reading JSON: %v\n", err)
		os.Exit(1)
	}

	// 2. Parse into internal map
	var configs map[string]ConfigRaw
	if err := json.Unmarshal(data, &configs); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Error unmarshaling: %v\n", err)
		os.Exit(1)
	}

	for code, cfg := range configs {
		if cfg.Decimals > MaxSafeDecimals {
			_, _ = fmt.Fprintf(os.Stderr, "WARNING: Skipping %s. Decimals (%d) exceeds MaxSafeDecimals (%d). Could be crypto that is not allowed, We must use a BigInt implementation for this currency.\n",
				code, cfg.Decimals, MaxSafeDecimals)
			delete(configs, code) // Remove from the map so it's not generated
			continue
		}
	}

	// 3. Generate the Go file
	f, err := os.Create("currencies.gen.go")
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer func(f *os.File) {
		err := f.Close()
		if err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "Error closing output file: %v\n", err)
			os.Exit(1)
		}
	}(f)

	tmpl := template.Must(template.New("gen").Parse(fileTemplate))
	if err := tmpl.Execute(f, configs); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Successfully generated currencies.gen.go")
}
